[package]
name = "wgpu"
version = "0.1.0"
authors = ["baptistemanson <baptiste.manson@inovia.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
winit = "0.24.0"
wgpu = "0.6.2"
futures = { version = "0.3", default-features = false, features = ["std"] }
# wgpu-subscriber = "0.1"


