[package]
name = "wgpu"
version = "0.1.0"
authors = ["baptistemanson <baptiste.manson@inovia.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
shaderc = "0.7"
winit = "0.24.0"
pollster = "0.2"
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
futures = { version = "0.3", default-features = false, features = ["std"] }
bytemuck = { version = "1.4", features = ["derive"] }

